#
# Configuration file for python sun-tracker
# Author: Chr. Monstein
# Date: 2023-08-21...23, updated 2024-12-23 (hot/cold individual positions)
# Do not add comments at the end of any parameter!
#

#------------------------------------------------------------------------------
# Location parameter
[Location]
longitude   = 8.7875
latitude    = 46.1723
elevation   = 374
temperature = 9.7
pressure    = 971.6

#------------------------------------------------------------------------------
# Tracker parameter (rotors and interface)
[Tracker]
max_range    = 77
azi_min      = 80.0
azi_max      = 250.0
ele_min      = -15.0
ele_max      = 90.0
azi_park     = 180
ele_park     = 89
azi_ref      = 186.3
ele_ref      = 60.5
azi_dir      = -1.0
ele_dir      = 1.0
plane_corr   = -0.0001
com_port   = COM4

#------------------------------------------------------------------------------
# Scanning parameter
[Coarse]
width_azi    = 10
width_ele  = 10
res_azi     = 0.5
res_ele      = 0.5
dwell_time  = 1
transition_time = 1

[Fine]
width_azi    = 3
width_ele  = 3
res_azi      = 0.1
res_ele      = 0.1
dwell_time  = 1
transition_time = 0.25